export default [
    { "value": "Select.." },
    { "value": "Non-Matriculation/O-Level" },
    { "value": "Intermediate/A-Leve" },
    { "value": "BA" },
    { "value": "BE" },
    { "value": "BFA" },
    { "value": "BBA" },
    { "value": "BS" },
    { "value": "BSC" },
    { "value": "BEd" },
    { "value": "BCom" },
    { "value": "BCom Hons" },
    { "value": "BDS" },
    { "value": "LLB" },
    { "value": "DNS" },
    { "value": "DVM" },
    { "value": "DPT" },
    { "value": "MA" },
    { "value": "ME" },
    { "value": "MS" },
    { "value": "MSc" },
    { "value": "MEd" },
    { "value": "LLM" },
    { "value": "MBA" },
    { "value": "MCom" },
    { "value": "MCom Hons" },
    { "value": "MFA" },
    { "value": "MPA" },
    { "value": "MBBS" },
    { "value": "Pharm-D" },
    { "value": "Mphil" },
    { "value": "PHD" },
    { "value": "Diploma" },
    { "value": "Certificate" },
    { "value": "Short Course" },

];