export default [
    { "value": "Select.." },
    { "value": "0.1" },
    { "value": "0.2" },
    { "value": "0.3" },
    { "value": "0.4" },
    { "value": "0.5" },
    { "value": "0.6" },
    { "value": "0.7" },
    { "value": "0.8" },
    { "value": "0.9" },
    { "value": "1.0" },
    { "value": "1.1" },
    { "value": "1.2" },
    { "value": "1.3" },
    { "value": "1.4" },
    { "value": "1.5" },
    { "value": "1.6" },
    { "value": "1.7" },
    { "value": "1.8" },
    { "value": "1.9" },
    { "value": "2.0" },
    { "value": "2.1" },
    { "value": "2.2" },
    { "value": "2.3" },
    { "value": "2.4" },
    { "value": "2.5" },
    { "value": "2.6" },
    { "value": "2.7" },
    { "value": "2.8" },
    { "value": "2.9" },
    { "value": "3.0" },
    { "value": "3.1" },
    { "value": "3.2" },
    { "value": "3.3" },
    { "value": "3.4" },
    { "value": "3.5" },
    { "value": "3.6" },
    { "value": "3.7" },
    { "value": "3.8" },
    { "value": "3.9" },
    { "value": "4.0" },


];