export default [
    { "value": "Select.." },
    { "value": "Accounting / Taxation" },
    { "value": "Advertising / PR" },
    { "value": "Agriculture / Fertilizer/ Pesticide" },
    { "value": "Apparel / Clothing" },
    { "value": "Architecture / Interior Design" },
    { "value": "Arts / Entertainment" },
    { "value": "Automobile" },
    { "value": "Aviation" },
    { "value": "Banking / Finacial Services" },
    { "value": "BPO" },
    { "value": "Broadcasting" },
    { "value": "Business Development" },
    { "value": "Call Center" },
    { "value": "Chemicals" },
    { "value": "Construction / Cement / Metals" },
    { "value": "Consultants" },
    { "value": "Courier / Logistics" },
    { "value": "Distribution and Logistics" },
    { "value": "DropShip" },
    { "value": "E-Commerce / E-Business" },
    { "value": "Education / Training" },
    { "value": "Electronics" },
    { "value": "Engineering" },
    { "value": "Event Management" },
    { "value": "Fashion" },
    { "value": "Fast Moving Consumer Goods" },
    { "value": "Food & Beverages" },
    { "value": "Gems & Jewelery" },
    { "value": "Government" },
    { "value": "Health & Fitness" },
    { "value": "HealthCare / Hospital / Medical" },
    { "value": "Hospitality" },
    { "value": "Hotel Management / Restaurent" },
    { "value": "importers / Distributors / Exporters" },
    { "value": "information Technology" },
    { "value": "Insurance / Takaful" },
    { "value": "Investments" },
    { "value": "Law Firms / Legal" },
    { "value": "Manufacturing" },
    { "value": "Media / Communications" },
    { "value": "Mining / Petroleum" },
    { "value": "N.G.O /Social Services" },
    { "value": "Oil & Gas/ Natural Resources" },
    { "value": "Packaging" },
    { "value": "Personal Care and Services" },
    { "value": "Pharmaceutical / Clinical Research" },
    { "value": "Power / Energy" },
    { "value": "Project Management" },
    { "value": "Publishing / Printing" },
    { "value": "Real Estate Property" },
    { "value": "Recruitment / Employment Firms" },
    { "value": "Retail" },
    { "value": "Security / Law Enforcement" },
    { "value": "Services" },
    { "value": "Shipping / Marine" },
    { "value": "Telecommunications / ISP" },
    { "value": "Textiles / Garments" },
    { "value": "Tiles & Ceramics" },
    { "value": "Travel / Tourism / Trasportation" },
    { "value": "Warehousing" },


];